version: "3.8"
services:

  minio:
    image: minio/minio
    restart: always
    container_name: sit-cc-minio
    volumes:
      - $HOME/mnt/storage/sit-careers:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    env_file: 
      - .minio.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3 
    networks:
      - sit-careers
      - sit-careers-api_sit-careers

networks:
  sit-careers:
    driver: bridge
  sit-careers-api_sit-careers:
    external: true